### ISSUE TITLE
How will I add normal menu items with expandable menus ?

### ISSUE THREAD

**Issue by nabeelpkl** [D8thReaper/android-navigation-menu-expandable#1]
Hi, I want to add normal menu items with expandable ones. I tried different methods. But nothing seems to be working.

**Comment by ayushpahwa** [comment]
Since I am using a normal ExpandableListView here, I think you can look for a solution which is centric on adding normal items in an ExpandanableListView. Refer [this](https://stackoverflow.com/questions/22574181/how-to-add-list-item-in-expandable-list-view).
